---
- name: Update | Copy settings.py to "{{ project.root }}/djavan"
  template:
    src: roles/django/templates/settings.py
    dest: "{{ project.root }}/djavan/settings.py"

- name: Update | Install djavan base requirements
  shell: . {{ project.virtualenv }}bin/activate && pip install -r ./requirements/base.txt chdir="{{ project.root }}"

- name: Update | Ensure "{{ project.root }}/manage.py" is Unicode
  shell: dos2unix "{{ project.root }}/manage.py"

- name: Update | Activate virtualenv venv and makemigrations
  shell: . {{ project.virtualenv }}bin/activate && {{ project.root }}/manage.py makemigrations chdir="{{ project.root }}"

- name: Update | Activate virtualenv venv and migrate
  shell: . {{ project.virtualenv }}bin/activate && ./manage.py migrate chdir="{{ project.root }}"

- name: Update | stop services
  service: name={{item}} state=stopped
  with_items:
    - uwsgi-{{project.name}}
    - nginx

- name: Update | start services
  service: name={{item}} state=started
  with_items:
    - nginx
    - uwsgi-{{project.name}}