const Constants = {
  WELCOME: 'WELCOME',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  VIEW_ASSESSMENTS: 'VIEW_ASSESSMENT',
  FETCH_ASSESSMENTS: 'FETCH_ASSESSMENTS',
  FETCH_ASSESSMENTS_REQUEST: 'FETCH_ASSESSMENTS_REQUEST',


};

export default Constants;
