const Constants = {
  WELCOME: 'WELCOME',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  VIEW_ASSESSMENT: 'VIEW_ASSESSMENT',
  FETCH_ASSESSMENTS: 'FETCH_ASSESSMENTS',
  FETCH_ASSESSMENTS_REQUEST: 'FETCH_ASSESSMENTS_REQUEST',
  FETCH_ASSESSMENTS_FAILURE: 'FETCH_ASSESSMENTS_FAILURE',
  UPDATE_ASSESSMENTS_LIST: 'UPDATE_ASSESSMENTS_LIST',
  REFRESH_ASSESSMENTS_LIST: 'REFRESH_ASSESSMENTS_LIST',
  VIEW_CLIENT: 'VIEW_CLIENT',
  FETCH_CLIENTS: 'FETCH_CLIENTS',
  FETCH_CLIENTS_REQUEST: 'FETCH_CLIENTS_REQUEST',
  FETCH_CLIENTS_FAILURE: 'FETCH_CLIENTS_FAILURE',
  UPDATE_CLIENTS_LIST: 'UPDATE_CLIENTS_LIST',
  REFRESH_CLIENTS_LIST: 'REFRESH_CLIENTS_LIST',
  TOGGLE_EDIT_VIEW: 'TOGGLE_EDIT_VIEW',
  FETCH_CLIENT: 'FETCH_CLIENT',
  FETCH_CLIENT_REQUEST: 'FETCH_CLIENT_REQUEST',
  FETCH_CLIENT_FAILURE: 'FETCH_CLIENT_FAILURE',

};

export default Constants;
