---
- name: nodejs | Download the nvm(node version manager) install script
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh dest=/tmp/install.sh

- name: nodejs | Install dependencies 
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  become: yes
  become_user: root

- name: nodejs | Execute the nvm install script
  shell: bash install.sh chdir=/tmp executable=/bin/bash

- name: nodejs | Register the NVM_DIR
  shell: echo $NVM_DIR
  register: nvm_dir 
  
- name: nodejs | create sym link for nvm-exec
  file:
    src: /root/.nvm/nvm-exec
    dest: /bin/nvm-exec
    state: link

- name: nodejs | create sym link for nvm
  file:
    src: /root/.nvm/nvm.sh
    dest: /bin/nvm
    state: link
    
- name: nodejs | Install the specified node version using the nvm command and set it as default
  shell: . /root/.nvm/nvm.sh && nvm install {{ version.nodejs_version }} && nvm run {{version.nodejs_version}} --version && nvm alias default {{version.nodejs_version}}
          creates=~/.nvm/versions/node/v{{ version.nodejs_version }} 
