---
- name: project | yarn
  shell: yarn
  args:
    chdir: "{{ project.root }}"

- name: project | npm install
  shell: "npm install --unsafe-perm"
  args:
      chdir: "{{ project.root }}"

- name: project | npm build
  shell: "npm build"
  args:
      chdir: "{{ project.root }}"