---
- name: project | yarn
  shell: yarn
  args:
    chdir: "{{ project.root }}"
  register: yarn
- debug: var=yarn.stdout_lines

- name: project | npm install
  shell: "npm install --unsafe-perm"
  args:
      chdir: "{{ project.root }}"
  register: yarn
- debug: var=yarn.stdout_lines

- name: project | npm run build
  shell: "npm run build"
  args:
      chdir: "{{ project.root }}"
  register: yarn
- debug: var=yarn.stdout_lines