---
- name: project | stop pm2
  systemd:
    name: pm2-root
    state: stopped

- name: project | remove "{{ project.root }}"
  file:
    path: "{{ project.root }}"
    state: absent
    
- name: project | Clone project
  git:
    repo: "{{ project.repo }}"
    dest: "{{ project.root }}"
    force: true
    update: no
    accept_hostkey: true
    version: "{{ project.repo_branch }}"
    when: {{ deploy }} == "manual"
    
- name: project | Unarchive djavan-fe application
  unarchive:
    src: files/djavan-fe-source.zip
    dest: "{{ project.root }}"
    copy: yes
    when: {{ deploy }} == "automated"

- name: project | Check if logs dir exists
  file:
    path: "{{ project.root }}/logs"
    state: directory

- name: project | set perms on "{{ project.root }}"
  file:
    group: "{{ project.group }}"
    owner: "{{ project.user }}"
    path: "{{ project.root }}"
    recurse: yes
    mode: 4775

- include: build.yml
