---
- name: project | Clone project
  git:
    repo: "{{ project.repo }}"
    dest: "{{ clone_tmpdir }}"
    force: true
    update: no
    accept_hostkey: true

- name: project | Prepare git files
  command: "mv -f {{ clone_tmpdir }}/.git/ {{ project.root }}/"

- name: project | Update project
  git:
    repo: "{{ project.repo }}"
    dest: "{{ project.root }}"
    force: true

- name: project | Check if logs dir exists
  file:
    path: "{{ project.root }}/logs"
    state: directory

- include: build.yml
