---
- name: project | Clone project
  git:
    repo: "{{ project.repo }}"
    dest: "{{ project.root }}"
    force: true
    update: no
    accept_hostkey: true
    version: "{{ project.repo_branch }}"

- name: project | Check if logs dir exists
  file:
    path: "{{ project.root }}/logs"
    state: directory

- include: build.yml
