---
- name: project | remove "{{ project.root }}"
  file:
    path: "{{ project.root }}"
    state: absent
    
- name: project | Clone project
  git:
    repo: "{{ project.repo }}"
    dest: "{{ project.root }}"
    force: true
    update: no
    accept_hostkey: true
    version: "{{ project.repo_branch }}"

- name: project | Check if logs dir exists
  file:
    path: "{{ project.root }}/logs"
    state: directory

- name: project | set perms on "{{ project.root }}"
  file:
    group: "{{ project.group }}"
    owner: "{{ project.user }}"
    path: "{{ project.root }}"
    recurse: yes
    mode: 4755

- include: build.yml
