---
hostname: djavan
domainname: rhino.lan

# General project variables
project:

  # The project's name. Generally does not need to be changed
  # Optional:
  name: djavan

  # The user below will be created as a Linux account to own the project directory and services like UWSGI. You may include the credentials for an existing user here if you wish.
  # This user will also be used to log into the Djavan web UI for the first time.
  # Recommended: "userPassword" should be changed for security purposes
  user: djavan
  userPassword: CHANGE_ME

  # Do not change this - sets the group to share access with services like UWSGI
  # IGNORE:
  group: www-data

  # These directories will be created, they do not need to exist prior to deployment. You may change them if you wish. They are used to hold the "in use" Djavan application files
  # Optional:
  root: /opt/djavan

# Definition of variables for ./roles/nginx/templates/nginx.conf
nginx:

  # Can be changed to total number of cores plus 1 for better performance
  # OPTIONAL: usually not necessary
  worker_processes: 2

#
#SSL Self Signed certs will only generate if set to true, an existing self signed cert does not exist and if a trusted cert does not exist in ./files/ssl/{{ssl_certs_common_name}}.*
ssl_certs_generate_self_signed: true

ssl_certs_country: "US"
ssl_certs_locality: "New York"
ssl_certs_organization: "Your company"
ssl_certs_state: "New York"
ssl_certs_common_name: "{{ hostname }}.{{ domainname }}"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

ssl_certs_path: "/etc/nginx/ssl/{{ssl_certs_common_name}}"
ssl_certs_path_owner: "www-data"
ssl_certs_path_group: "www-data"
ssl_certs_privkey_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.key"
ssl_certs_cert_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.pem"
ssl_certs_csr_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.csr"
ssl_certs_dhparam_path: "{{ssl_certs_path}}/dhparam.pem"
ssl_certs_mode: "0700"

ssl_certs_local_privkey_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/{{ssl_certs_common_name}}.key"
ssl_certs_local_cert_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/{{ssl_certs_common_name}}.pem"


ssl_certs_key_size: "2048"
ssl_certs_generate_dh_param: false
ssl_certs_dhparam_size: "2048"